"""Access to the committed flag sprite.

``static/gentelella/flags/flags.4x3.svg.gz`` holds all 266 flag-icons flags as
``<symbol>`` elements. It ships in the package, so nothing is downloaded at
build or install time; the helpers here decompress it once per process and index
it by country code for :mod:`djgentelella.views.flags` and the ``gtflags``
template tags.
"""
import gzip
import re
from functools import lru_cache
from urllib.parse import urlencode

from django.contrib.staticfiles import finders
from django.core.exceptions import ImproperlyConfigured
from django.urls import reverse

from djgentelella import __version__

SPRITE_STATIC_PATH = 'gentelella/flags/flags.4x3.svg.gz'

SYMBOL = re.compile(
    r'<symbol id="fi-([^"]+)" viewBox="([^"]+)"[^>]*>(.*?)</symbol>', re.DOTALL)


@lru_cache(maxsize=1)
def get_sprite_bytes():
    """The sprite exactly as committed -- still gzipped.

    Returned as-is so the sprite view can hand these bytes to the browser under
    ``Content-Encoding: gzip`` without recompressing them on every request.
    """
    path = finders.find(SPRITE_STATIC_PATH)
    if path is None:
        raise ImproperlyConfigured(
            "%s not found. It ships with djgentelella, so this usually means "
            "'djgentelella' is missing from INSTALLED_APPS or a stale "
            "collectstatic. Run `manage.py buildflagsprite` to regenerate it."
            % SPRITE_STATIC_PATH)
    with open(path, 'rb') as sprite:
        return sprite.read()


@lru_cache(maxsize=1)
def get_index():
    """``{code: (viewBox, body)}`` for every flag in the sprite.

    Roughly 2.4 MB resident, built once. Regex rather than a real XML parse: the
    file is machine-generated by ``buildflagsprite`` in exactly this shape, and
    ElementTree would cost several times the memory for no gain.
    """
    raw = gzip.decompress(get_sprite_bytes()).decode('utf-8')
    return {code: (viewbox, body) for code, viewbox, body in SYMBOL.findall(raw)}


def get_flag_codes():
    """Every code the sprite can serve, as a frozenset."""
    return frozenset(get_index())


def flag_url(code, **params):
    """URL of a single flag, for ``<img src>`` and select2 ``get_url()``.

    Carries the package version so an upgraded sprite is not masked by the
    long-lived cache headers the view sets, the same way ``?v=`` busts the
    bundles in ``gentelella/statics/stylesheets.html``.
    """
    params.setdefault('v', __version__)
    return '%s?%s' % (reverse('flag_icon', kwargs={'code': code}),
                      urlencode(params))
