"""Regenerate the committed flag sprite.

This is a *maintenance* command, not a build step: the sprite it writes,
``static/gentelella/flags/flags.4x3.svg.gz``, is committed to the repository and
shipped as-is. Run it only when ``FLAG_ICONS_VERSION`` is bumped.

The alternative it replaces was downloading 533 files from a CDN on every
``loaddevstatic`` and base64-inlining them into a 6.35 MB stylesheet, which the
browser had to load in full to show a single flag.
"""
import gzip
import re
from pathlib import Path

from django.core.management import BaseCommand, CommandError

try:
    import requests
except BaseException:  # pragma: no cover - same guard as loaddevstatic
    print('Requests is required try pip install requests')
    exit(1)

FLAG_ICONS_VERSION = '6.6.6'
CDN_URL = ('https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/%s/flags/4x3/'
           '%s.svg')

# Every code flag-icons 6.6.6 draws. Kept here rather than derived from the
# sprite: this is the input list, and a code silently dropping off it is exactly
# what the completeness check below is for.
FLAGS = ['ac', 'ad', 'ae', 'af', 'ag', 'ai', 'al', 'am', 'ao', 'aq', 'ar', 'as', 'at',
         'au', 'cp', 'dg', 'ea', 'es-ct', 'es-ga', 'ic', 'ta',
         'aw', 'ax', 'az', 'ba', 'bb', 'bd', 'be', 'bf', 'bg', 'bh', 'bi', 'bj', 'bl',
         'bm', 'bn', 'bo', 'bq', 'br', 'bs', 'bt', 'bv', 'bw', 'by', 'bz', 'ca', 'cc',
         'cd', 'cefta', 'cf', 'cg', 'ch', 'ci', 'ck', 'cl', 'cm', 'cn', 'co', 'cr',
         'cu', 'cv',
         'cw', 'cx', 'cy', 'cz', 'de', 'dj', 'dk', 'dm', 'do', 'dz', 'ec', 'ee', 'eg',
         'eh', 'er', 'es', 'et', 'eu', 'fi', 'fj', 'fk', 'fm', 'fo', 'fr',
         'ga', 'gb-eng', 'gb-nir', 'gb-sct', 'gb-wls', 'gb', 'gd', 'ge', 'gf', 'gg',
         'gh', 'gi', 'gl', 'gm', 'gn', 'gp', 'gq', 'gr', 'gs', 'gt', 'gu', 'gw', 'gy',
         'hk', 'hm', 'hn', 'hr', 'ht', 'hu', 'id', 'ie', 'il', 'im', 'in', 'io', 'iq',
         'ir', 'is', 'it', 'je', 'jm', 'jo', 'jp', 'ke', 'kg', 'kh', 'ki', 'km', 'kn',
         'kp', 'kr', 'kw', 'ky', 'kz', 'la', 'lb', 'lc', 'li', 'lk', 'lr', 'ls', 'lt',
         'lu', 'lv', 'ly', 'ma', 'mc', 'md', 'me', 'mf', 'mg', 'mh', 'mk', 'ml', 'mm',
         'mn', 'mo', 'mp', 'mq', 'mr', 'ms', 'mt', 'mu', 'mv', 'mw', 'mx', 'my', 'mz',
         'na', 'nc', 'ne', 'nf', 'ng', 'ni', 'nl', 'no', 'np', 'nr', 'nu', 'nz', 'om',
         'pa', 'pe', 'pf', 'pg', 'ph', 'pk', 'pl', 'pm', 'pn', 'pr', 'ps', 'pt', 'pw',
         'py', 'qa', 're', 'ro', 'rs', 'ru', 'rw', 'sa', 'sb', 'sc', 'sd', 'se', 'sg',
         'sh', 'si', 'sj', 'sk', 'sl', 'sm', 'sn', 'so', 'sr', 'ss', 'st', 'sv', 'sx',
         'sy', 'sz', 'tc', 'td', 'tf', 'tg', 'th', 'tj', 'tk', 'tl', 'tm', 'tn', 'to',
         'tr', 'tt', 'tv', 'tw', 'tz', 'ua', 'ug', 'um', 'un', 'us', 'uy', 'uz', 'va',
         'vc', 've', 'vg', 'vi', 'vn', 'vu', 'wf', 'ws', 'xk', 'xx', 'ye', 'yt', 'za',
         'zm', 'zw']

SPRITE_PATH = (Path(__file__).resolve().parents[2]
               / 'static' / 'gentelella' / 'flags' / 'flags.4x3.svg.gz')

SPRITE_HEADER = (
    '<svg xmlns="http://www.w3.org/2000/svg" '
    'xmlns:xlink="http://www.w3.org/1999/xlink" style="display:none">'
    '<!-- flag-icons %s, 4x3, generated by manage.py buildflagsprite -->'
)

ROOT_TAG = re.compile(r'<svg\b[^>]*>')
VIEWBOX = re.compile(r'viewBox="([^"]+)"')
ID_ATTR = re.compile(r'\bid="([^"]+)"')
COMMENT = re.compile(r'<!--.*?-->', re.DOTALL)
PROLOG = re.compile(r'<\?xml.*?\?>|<!DOCTYPE[^>]*>', re.DOTALL)
BETWEEN_TAGS = re.compile(r'>\s+<')


def _is_html_error_page(content):
    # Same guard as loaddevstatic: some CDN paths answer a dead URL with 200 and
    # an HTML page, and status alone won't catch that.
    head = content[:512].lstrip().lower()
    return head.startswith(b'<!doctype html') or head.startswith(b'<html')


def build_symbol(code, source):
    """Turn one flag-icons SVG into a ``<symbol>`` safe to sit beside 265 others.

    Every internal id is prefixed with the flag code. 140 of the 266 files carry
    internal ids -- ``ai.svg`` alone has 760 -- and 137 point at them through
    ``<use>``, ``clip-path`` or ``fill``, so concatenating them untouched makes
    flags borrow each other's gradients and clip paths.
    """
    source = PROLOG.sub('', COMMENT.sub('', source))
    root = ROOT_TAG.search(source)
    if root is None:
        raise ValueError('no <svg> root element')
    viewbox = VIEWBOX.search(root.group(0))
    if viewbox is None:
        raise ValueError('root <svg> has no viewBox')

    body = source[root.end():source.rindex('</svg>')]
    # Longest first: an id that is a prefix of another must not be rewritten
    # inside it.
    for name in sorted(set(ID_ATTR.findall(body)), key=len, reverse=True):
        body = body.replace('id="%s"' % name, 'id="%s-%s"' % (code, name))
        body = body.replace('#%s"' % name, '#%s-%s"' % (code, name))
        body = body.replace('url(#%s)' % name, 'url(#%s-%s)' % (code, name))

    body = BETWEEN_TAGS.sub('><', body).strip()
    # `slice` is a no-op in a 4:3 box, where these flags are drawn, and crops the
    # sides in a square one -- which is what makes .gt-flag-square work without
    # a second set of 1x1 artwork. A <use> cannot override a symbol's
    # preserveAspectRatio, so it has to be set here.
    return ('<symbol id="fi-%s" viewBox="%s" '
            'preserveAspectRatio="xMidYMid slice">%s</symbol>') % (
        code, viewbox.group(1), body)


class Command(BaseCommand):
    help = ('Rebuild static/gentelella/flags/flags.4x3.svg.gz from flag-icons '
            '%s. Only needed when that version changes.' % FLAG_ICONS_VERSION)

    def add_arguments(self, parser):
        parser.add_argument(
            '--source-dir',
            help='Read <code>.svg from this directory instead of the CDN.',
        )
        parser.add_argument(
            '--output',
            default=str(SPRITE_PATH),
            help='Where to write the sprite (default: %s)' % SPRITE_PATH,
        )

    def read_flag(self, code, source_dir):
        if source_dir:
            path = Path(source_dir) / ('%s.svg' % code)
            if not path.is_file():
                raise ValueError('missing %s' % path)
            return path.read_text(encoding='utf-8')

        response = requests.get(CDN_URL % (FLAG_ICONS_VERSION, code), timeout=30)
        if not response.ok:
            raise ValueError('HTTP %s' % response.status_code)
        if _is_html_error_page(response.content):
            raise ValueError('CDN answered with an HTML page')
        return response.content.decode('utf-8')

    def handle(self, *args, **options):
        source_dir = options['source_dir']
        symbols = []
        failures = []
        for code in sorted(FLAGS):
            try:
                symbols.append(build_symbol(code, self.read_flag(code, source_dir)))
            except (ValueError, OSError, UnicodeDecodeError) as exc:
                failures.append('%s: %s' % (code, exc))
            else:
                self.stdout.write('.', ending='')
                self.stdout.flush()
        self.stdout.write('')

        if failures:
            # The sprite is committed, so a short one would be a gap living in
            # the repository until somebody noticed a blank flag in production.
            raise CommandError(
                '%d of %d flags could not be built, refusing to write a '
                'partial sprite:\n  %s' % (
                    len(failures), len(FLAGS), '\n  '.join(failures)))

        sprite = ((SPRITE_HEADER % FLAG_ICONS_VERSION)
                  + ''.join(symbols) + '</svg>').encode('utf-8')
        output = Path(options['output'])
        output.parent.mkdir(parents=True, exist_ok=True)
        # mtime=0 so rebuilding an unchanged sprite produces identical bytes and
        # does not show up as a diff.
        with gzip.GzipFile(str(output), 'wb', compresslevel=9, mtime=0) as arch:
            arch.write(sprite)

        self.stdout.write(self.style.SUCCESS(
            '%s: %d flags, %d bytes raw, %d bytes gzipped' % (
                output, len(symbols), len(sprite), output.stat().st_size)))
