# Generated by Django 5.0.4 on 2024-05-10 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Requested'), (1, 'Borrowed'), (2, 'Denied'), (3, 'Selected'), (4, 'Returned')], default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='DescriptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.SmallIntegerField(choices=[(0, 'Building'), (1, 'Requested'), (2, 'Accepted'), (3, 'Denied'), (4, 'Borrowed'), (5, 'Returned')], default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(null=True)),
                ('action_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
            ],
        ),
    ]
