# Generated by Django 3.0.2 on 2020-06-06 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djgentelella.fields.catalog


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)])),
                ('speed_in_miles_per_hour', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('number_of_eyes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='WithCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', djgentelella.fields.catalog.GTManyToManyField(related_name='countryrel', to='demoapp.Catalog')),
                ('mycatalog', djgentelella.fields.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demoapp.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('num_children', models.IntegerField(default=0)),
                ('born_date', models.DateField()),
                ('last_time', models.DateTimeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='OneCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', djgentelella.fields.catalog.GTOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demoapp.Catalog')),
            ],
        ),
    ]
