# Generated by Django 3.0.2 on 2020-04-20 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='County',
            new_name='Country',
        ),
    ]
