# Generated by Django 3.0.6 on 2020-05-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20200420_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('speed_in_miles_per_hour', models.FloatField()),
                ('number_of_eyes', models.IntegerField()),
            ],
        ),
    ]
