# Generated by Django 3.0.2 on 2020-05-25 06:10

from django.db import migrations, models
import django.db.models.deletion
import djgentelella.fields.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20200420_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WithCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', djgentelella.fields.catalog.GTManyToManyField(related_name='countryrel', to='demoapp.Catalog')),
                ('mycatalog', djgentelella.fields.catalog.GTForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demoapp.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='OneCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', djgentelella.fields.catalog.GTOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demoapp.Catalog')),
            ],
        ),
    ]
