# Generated by Django 3.0.2 on 2020-06-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('demoapp', '0003_auto_20200616_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplegroup',
            name='country',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='demoapp.Country'),
        ),
    ]
