# Generated by Django 3.0.6 on 2020-05-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_foo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foo',
            name='age',
            field=models.IntegerField(validators=[]),
        ),
        migrations.AlterField(
            model_name='foo',
            name='number_of_eyes',
            field=models.IntegerField(validators=[]),
        ),
        migrations.AlterField(
            model_name='foo',
            name='speed_in_miles_per_hour',
            field=models.FloatField(validators=[]),
        ),
    ]
