# Generated by Django 3.0.6 on 2020-05-20 03:24

import demoapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_foo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foo',
            name='age',
            field=models.IntegerField(validators=[demoapp.validators.validate_age_value]),
        ),
        migrations.AlterField(
            model_name='foo',
            name='number_of_eyes',
            field=models.IntegerField(validators=[demoapp.validators.validate_eyes_number]),
        ),
        migrations.AlterField(
            model_name='foo',
            name='speed_in_miles_per_hour',
            field=models.FloatField(validators=[demoapp.validators.validate_speed_value]),
        ),
    ]
