# Generated by Django 3.0.2 on 2020-06-21 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_peoplegroup_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=150)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.A')),
            ],
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=150)),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.B')),
            ],
        ),
        migrations.CreateModel(
            name='D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=150)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.C')),
            ],
        ),
        migrations.CreateModel(
            name='E',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=150)),
                ('d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.D')),
            ],
        ),
        migrations.CreateModel(
            name='ABCDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.ManyToManyField(to='demoapp.A')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.B')),
                ('c', models.ManyToManyField(to='demoapp.C')),
                ('d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.D')),
                ('e', models.ManyToManyField(to='demoapp.E')),
            ],
        ),
    ]
