# Generated by Django 3.1 on 2020-08-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_a_abcde_b_c_d_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('custom', models.CharField(max_length=10)),
                ('serial_number', models.CharField(max_length=25)),
                ('taxid', models.CharField(max_length=25)),
                ('credit_card', models.CharField(max_length=25)),
            ],
        ),
    ]
