# Generated by Django 3.0.8 on 2020-08-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_a_abcde_b_c_d_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.Person')),
            ],
        ),
    ]
