# Generated by Django 3.1 on 2020-09-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_daterange'),
    ]

    operations = [
        migrations.CreateModel(
            name='gridSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevent_dragging', models.CharField(max_length=20)),
                ('pre_defined_steps', models.CharField(max_length=20)),
                ('default_min_and_max', models.CharField(max_length=20)),
                ('minimum_and_maximum_values', models.CharField(max_length=20)),
                ('hours', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='daterange',
            name='date_time',
            field=models.CharField(max_length=45),
        ),
    ]
