# Generated by Django 3.0.8 on 2020-09-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_daterange'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_list', models.CharField(blank=True, max_length=500, null=True)),
                ('email_list', models.CharField(blank=True, max_length=500, null=True)),
                ('area_list', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='daterange',
            name='date_time',
            field=models.CharField(max_length=45),
        ),
    ]
