# Generated by Django 3.1 on 2020-09-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_auto_20200915_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gridslider',
            old_name='maximun',
            new_name='maximum',
        ),
        migrations.RenameField(
            model_name='gridslider',
            old_name='minimun',
            new_name='minimum',
        ),
    ]
