# Generated by Django 3.1.2 on 2020-10-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('demoapp', '0009_wysiwygmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesNoInput',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('has_copies', models.BooleanField(default=False)),
                ('copy_number', models.IntegerField(default=0)),
                ('has_meta', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=2020)),
                ('editorial', models.CharField(default='', max_length=250)),
                ('display_publish', models.BooleanField(default=False)),
            ],
        ),
    ]
