# Generated by Django 3.1 on 2020-10-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0010_yesnoinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiwidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=25)),
                ('passport', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
