# Generated by Django 3.0.8 on 2020-10-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_auto_20200916_1352'),
        ('demoapp', '0010_yesnoinput'),
    ]

    operations = [
    ]
