# Generated by Django 3.1 on 2020-10-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0010_yesnoinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='gridSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
