# Generated by Django 3.1.2 on 2020-12-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0010_yesnoinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='wysiwygmodel',
            name='extra_information',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
