# Generated by Django 3.1.11 on 2021-05-31 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0011_wysiwygmodel_extra_information'),
        ('demoapp', '0011_merge_20201016_1813'),
    ]

    operations = [
    ]
