# Generated by Django 3.1 on 2020-10-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0011_gridslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridslider',
            name='maximum',
        ),
        migrations.RemoveField(
            model_name='gridslider',
            name='minimum',
        ),
        migrations.AddField(
            model_name='gridslider',
            name='ranges',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
