# Generated by Django 3.2.3 on 2021-05-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_auto_20200916_1352'),
        ('demoapp', '0011_wysiwygmodel_extra_information'),
    ]

    operations = [
    ]
