# Generated by Django 3.1 on 2020-10-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0012_countries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
