# Generated by Django 3.1 on 2020-10-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0012_auto_20201018_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridslider',
            name='ranges',
        ),
        migrations.AddField(
            model_name='gridslider',
            name='maximum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gridslider',
            name='minimum',
            field=models.IntegerField(default=0),
        ),
    ]
