# Generated by Django 3.1.3 on 2021-06-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('demoapp', '0013_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUploadItem',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fileexample', models.FileField(upload_to='filedemo')),
            ],
        ),
    ]
