# Generated by Django 3.1 on 2020-10-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0013_auto_20201018_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridslider',
            name='datetime',
            field=models.CharField(max_length=30),
        ),
    ]
