# Generated by Django 3.1 on 2020-10-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0014_auto_20201020_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridslider',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
