# Generated by Django 4.1.2 on 2023-01-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0015_calendar_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colors',
        ),
    ]
