# Generated by Django 3.1 on 2020-10-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0015_auto_20201020_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridslider',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
