# Generated by Django 3.2.11 on 2022-01-19 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0015_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('options', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='demoapp.calendar'),
            preserve_default=False,
        ),
    ]
