# Generated by Django 4.2.3 on 2023-10-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_relperson'),
        ('demoapp', '0016_delete_colors'),
    ]

    operations = [
    ]
