# Generated by Django 3.2.11 on 2022-01-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0016_auto_20220119_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
