# Generated by Django 4.1.7 on 2023-03-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0016_delete_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='selectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
