# Generated by Django 3.2.11 on 2022-01-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0017_alter_calendar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='events',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
