# Generated by Django 4.2.3 on 2023-09-29 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0017_objectmanagerdemomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectmanagerdemomodel',
            name='grid_slider',
        ),
        migrations.RemoveField(
            model_name='objectmanagerdemomodel',
            name='gridslider_maximum',
        ),
        migrations.RemoveField(
            model_name='objectmanagerdemomodel',
            name='gridslider_minimum',
        ),
    ]
