# Generated by Django 4.2.11 on 2025-03-20 16:21

from django.db import migrations, models
import djgentelella.fields.multiwidget


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0017_objectmanagerdemomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiWidgetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='a name', max_length=150)),
                ('widget_type', models.CharField(default='NumberInput', max_length=150)),
                ('json_field', djgentelella.fields.multiwidget.MultiWidgetJsonField(blank=True, null=True)),
            ],
        ),
    ]
