# Generated by Django 4.2.11 on 2025-05-22 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0018_digitalsignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.FileField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_image', models.ManyToManyField(blank=True, related_name='imges_x', to='demoapp.selectimage')),
                ('related_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_img', to='demoapp.selectimage')),
            ],
        ),
    ]
