# Generated by Django 4.2.3 on 2023-09-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0018_remove_objectmanagerdemomodel_grid_slider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmanagerdemomodel',
            name='taging_list',
            field=models.CharField(max_length=256),
        ),
    ]
