# Generated by Django 5.1.5 on 2025-05-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0018_digitalsignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.FileField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
