# Generated by Django 5.1.6 on 2025-08-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0019_customer'),
        ('demoapp', '0019_selectimage_img'),
    ]

    operations = [
    ]
