# Generated by Django 5.1.5 on 2025-05-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0019_selectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imges_x', models.ManyToManyField(blank=True, related_name='imges_x', to='demoapp.selectimage')),
            ],
        ),
    ]
