# Generated by Django 4.2.11 on 2025-05-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0020_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='imges_x',
            new_name='multi_image',
        ),
        migrations.AddField(
            model_name='img',
            name='related_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_img', to='demoapp.selectimage'),
        ),
    ]
