# Generated by Django 5.2.5 on 2026-07-25 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0020_merge_0019_customer_0019_selectimage_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectManagerDemoNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('demo_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='demoapp.objectmanagerdemomodel')),
            ],
        ),
    ]
