# Generated by Django 5.2.5 on 2026-08-16 21:19

import djgentelella.fields.maps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0021_objectmanagerdemonote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('location', djgentelella.fields.maps.GTPointField(based_fields=['#id_country', '#id_city'], blank=True, center=(9.9327, -84.0875), search=True, zoom=8)),
            ],
        ),
    ]
