# Generated by Django 5.2.5 on 2026-08-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0024_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
