# Generated by Django 5.2.5 on 2026-08-27 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0025_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='img_countries', to='demoapp.country'),
        ),
        migrations.AddField(
            model_name='img',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_country', to='demoapp.country'),
        ),
    ]
