# Generated by Django 5.2.5 on 2026-02-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0026_img_countries_img_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfdocuments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PDF Document',
                'verbose_name_plural': 'PDF Documents',
            },
        ),
    ]
