# Generated by Django 5.2.5 on 2026-08-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0027_pdfdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkeduploaditem',
            name='fileexample',
            field=models.FileField(blank=True, upload_to='filedemo'),
        ),
    ]
