# Generated by Django 5.2.5 on 2026-08-30 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0028_alter_chunkeduploaditem_fileexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('shape', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('content', models.CharField(blank=True, default='', max_length=150)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('row', models.PositiveSmallIntegerField(default=0)),
                ('col', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='demoapp.warehouse')),
            ],
            options={
                'ordering': ['row', 'col', 'order', 'pk'],
            },
        ),
    ]
