# Generated by Django 3.2.4 on 2021-06-26 20:31

from django.db import migrations


def forwards_func(apps, schema_editor):
    Settings = apps.get_model("djgentelella", "GentelellaSettings")
    Settings.objects.create(
        key='use_compress_static',
        value='true'
    )


class Migration(migrations.Migration):
    dependencies = [
        ('djgentelella', '0003_alter_chunkedupload_status'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
