# Generated by Django 4.1.2 on 2023-01-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djgentelella', '0001_squashed_new_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionscategorymanagement',
            options={'permissions': [('can_manage_permissions', 'Can manage permissions')]},
        ),
    ]
