# Generated by Django 4.1.2 on 2023-03-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgentelella', '0002_alter_permissionscategorymanagement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedupload',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Subiendo'), (2, 'Completo')], default=1),
        ),
    ]
