# Generated by Django 3.0.2 on 2020-04-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgentelella', '0003_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='help_title',
            field=models.CharField(default='without title', help_text='Title to show with help', max_length=350),
            preserve_default=False,
        ),
    ]
