# Generated by Django 3.0.2 on 2020-04-22 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djgentelella', '0004_loadsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('link', models.URLField(verbose_name='Link')),
                ('message_type', models.CharField(choices=[('default', 'Default'), ('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], max_length=150, verbose_name='Message Type')),
                ('state', models.CharField(choices=[('visible', 'Visible'), ('hide', 'Hidden')], default='visible', max_length=150, verbose_name='State')),
                ('category', models.UUIDField(blank=True, null=True, verbose_name='Category')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
