# Generated by Django 3.1.3 on 2020-11-21 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djgentelella', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTDbForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('representation_list', models.CharField(choices=[('as_table', 'As Table'), ('as_p', 'As P'), ('as_ul', 'As ul'), ('as_inline', 'As Inline'), ('as_horizontal', 'As Horizontal'), ('as_plain', 'As Plain')], default='as_table', max_length=50)),
                ('template_name', models.CharField(default='default', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GTDbField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('required', models.BooleanField(default=True)),
                ('label_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('help_text', models.CharField(blank=True, max_length=500, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('extra_attr', models.JSONField(blank=True, null=True)),
                ('extra_kwarg', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djgentelella.gtdbform')),
            ],
        ),
    ]
