# Generated by Django 3.1.11 on 2021-05-31 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('djgentelella', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsCategoryManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('url_name', models.CharField(max_length=50, verbose_name='Url Name')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission', verbose_name='Permission')),
            ],
        ),
    ]
