# Generated by Django 3.2.4 on 2021-06-26 20:31

from django.db import migrations

def forwards_func(apps, schema_editor):
    Settings = apps.get_model("djgentelella", "GentelellaSettings")
    Settings.objects.create(
        key='site_theme',
        value='gentelella/css/custom.css'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('djgentelella', '0007_edit_footer'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
