# Generated by Django 4.1.1 on 2022-10-08 01:43

from django.db import migrations, models

def gen_position(apps, schema_editor):
    MenuItem = apps.get_model('djgentelella', 'MenuItem')
    for obj in MenuItem.objects.all():
        obj.position = obj.tree_id * 100000 + obj.lft
        obj.save(update_fields=['position'])

class Migration(migrations.Migration):

    dependencies = [
        ('djgentelella', '0009_chunkedupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(gen_position, reverse_code=migrations.RunPython.noop),
    ]
