# Generated by Django 4.1.1 on 2022-10-08 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djgentelella', '0010_menuitem_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='level',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='djgentelella.menuitem', verbose_name='parent'),
        ),
    ]
