# Generated by Django 4.2.3 on 2023-10-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djgentelella', '00012_defaultusecompessstatic'),
        ('djgentelella', '0006_gtdbfield_gtdbform'),
    ]

    operations = [
    ]
