# Generated by Django 5.1.6 on 2025-08-03 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgentelella', '0015_trash_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
