# Generated by Django 5.2.5 on 2025-08-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgentelella', '0016_trash_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedupload',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Uploading'), (2, 'Complete')], default=1),
        ),
    ]
