# Generated by Django 5.2.5 on 2025-08-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgentelella', '0017_alter_chunkedupload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedupload',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Subiendo'), (2, 'Completo')], default=1),
        ),
    ]
