# Generated by Django 5.2.8 on 2026-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgentelella', '0018_alter_chunkedupload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedupload',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Uploading'), (2, 'Complete')], default=1),
        ),
    ]
