# Generated by Django 5.2.5 on 2026-08-30 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('djgentelella', '0018_alter_chunkedupload_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Data')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gt_relations', to='admin.logentry', verbose_name='Log entry')),
            ],
            options={
                'verbose_name': 'History relation',
                'verbose_name_plural': 'History relations',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='djgentelell_content_889185_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('content_type__isnull', False), ('object_id__isnull', False)), models.Q(('content_type__isnull', True), ('data__isnull', False), ('object_id__isnull', True)), _connector='OR'), name='gt_historyrelation_valid_row')],
            },
        ),
    ]
