# Generated by Django 5.2.5 on 2026-08-30 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djgentelella', '0019_historyrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='Object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
                ('trash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gt_relations', to='djgentelella.trash', verbose_name='Trash entry')),
            ],
            options={
                'verbose_name': 'Trash relation',
                'verbose_name_plural': 'Trash relations',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='djgentelell_content_f5dfc0_idx')],
            },
        ),
    ]
