# Generated by Django 5.2.5 on 2026-02-14 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Unique identifier for this template', max_length=150, unique=True, verbose_name='Code')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('message', models.TextField(help_text='HTML content with Django template syntax', verbose_name='Message')),
                ('bcc', models.TextField(blank=True, default='', verbose_name='BCC')),
                ('cc', models.TextField(blank=True, default='', verbose_name='CC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsLetterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('message', models.TextField(help_text='HTML content for the newsletter template', verbose_name='Message')),
                ('model_base', models.CharField(blank=True, default='', help_text='Key from ASYNC_NEWS_BASE_MODELS settings', max_length=255, verbose_name='Model Base')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Template',
                'verbose_name_plural': 'Newsletter Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('file', models.FileField(upload_to='async_notification/attachments/%Y/%m/%d/', verbose_name='File')),
                ('is_inline', models.BooleanField(default=False, help_text='If True, embedded as inline image (cid:)', verbose_name='Is Inline')),
                ('content_id', models.CharField(blank=True, default='', help_text='Content-ID for inline attachments', max_length=255, verbose_name='Content ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Attached File',
                'verbose_name_plural': 'Attached Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('recipients', models.TextField(help_text='Comma-separated email addresses or group references', verbose_name='Recipients')),
                ('bcc', models.TextField(blank=True, default='', verbose_name='BCC')),
                ('cc', models.TextField(blank=True, default='', verbose_name='CC')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('recipients_raw', models.TextField(blank=True, default='', help_text='Resolved email addresses after processing', verbose_name='Resolved Recipients')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('enqueued', models.BooleanField(default=True, help_text='If True, processed by backend/cron. If False, sent immediately via signal.', verbose_name='Enqueued')),
                ('send_individually', models.BooleanField(default=False, help_text='Send one email per recipient instead of batching', verbose_name='Send Individually')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('recipients', models.TextField(help_text='Comma-separated email addresses or group references', verbose_name='Recipients')),
                ('bcc', models.TextField(blank=True, default='', verbose_name='BCC')),
                ('cc', models.TextField(blank=True, default='', verbose_name='CC')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='async_notification/newsletter/%Y/%m/%d/', verbose_name='Attached File')),
                ('filters_querystring', models.TextField(blank=True, default='', help_text='Querystring for filtering recipients', verbose_name='Filters Querystring')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='async_notification.newslettertemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsLetterTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(verbose_name='Send Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('revoked', 'Revoked')], default='pending', max_length=20, verbose_name='Status')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery Task ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='async_notification.newsletter', verbose_name='Newsletter')),
            ],
            options={
                'verbose_name': 'Newsletter Task',
                'verbose_name_plural': 'Newsletter Tasks',
                'ordering': ['-send_date'],
            },
        ),
    ]
