# Generated by Django 5.2.5 on 2026-07-22 20:21

import json

import djgentelella.async_notification.models
from django.conf import settings
from django.db import migrations, models


def convert_csv_to_lists(apps, schema_editor):
    """Convert legacy comma-separated recipients/bcc/cc text to JSON lists.

    Runs while the columns are still TextField, encoding each value as a
    JSON array so the subsequent AlterField-to-JSONField reads cleanly.
    """
    for model_name in ('EmailNotification', 'NewsLetter'):
        Model = apps.get_model('async_notification', model_name)
        for obj in Model.objects.all():
            changed = False
            for field in ('recipients', 'bcc', 'cc'):
                value = getattr(obj, field)
                if isinstance(value, str):
                    items = [i.strip() for i in value.split(',') if i.strip()]
                    setattr(obj, field, json.dumps(items))
                    changed = True
            if changed:
                obj.save(update_fields=['recipients', 'bcc', 'cc'])


def convert_lists_to_csv(apps, schema_editor):
    """Reverse: turn JSON list values back into comma-separated text."""
    for model_name in ('EmailNotification', 'NewsLetter'):
        Model = apps.get_model('async_notification', model_name)
        for obj in Model.objects.all():
            changed = False
            for field in ('recipients', 'bcc', 'cc'):
                value = getattr(obj, field)
                if isinstance(value, str):
                    try:
                        parsed = json.loads(value)
                    except (ValueError, TypeError):
                        continue
                    if isinstance(parsed, list):
                        setattr(obj, field, ', '.join(str(i) for i in parsed))
                        changed = True
            if changed:
                obj.save(update_fields=['recipients', 'bcc', 'cc'])


class Migration(migrations.Migration):

    dependencies = [
        ('async_notification', '0002_emailtemplate_context_code_base_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(convert_csv_to_lists, convert_lists_to_csv),
        migrations.RemoveField(
            model_name='emailnotification',
            name='sent',
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='base_template',
            field=models.CharField(blank=True, default='', help_text='Base template key from settings to wrap the email body', max_length=150, verbose_name='Base Template'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='last_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Attempt'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='Maximum number of send attempts before failing', verbose_name='Max Retries'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='bcc',
            field=models.JSONField(blank=True, default=list, validators=[djgentelella.async_notification.models.validate_recipient_list], verbose_name='BCC'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='cc',
            field=models.JSONField(blank=True, default=list, validators=[djgentelella.async_notification.models.validate_recipient_list], verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='recipients',
            field=models.JSONField(blank=True, default=list, help_text='List of email addresses or group references', validators=[djgentelella.async_notification.models.validate_recipient_list], verbose_name='Recipients'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='bcc',
            field=models.JSONField(blank=True, default=list, validators=[djgentelella.async_notification.models.validate_recipient_list], verbose_name='BCC'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='cc',
            field=models.JSONField(blank=True, default=list, validators=[djgentelella.async_notification.models.validate_recipient_list], verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='recipients',
            field=models.JSONField(blank=True, default=list, help_text='List of email addresses or group references', validators=[djgentelella.async_notification.models.validate_recipient_list], verbose_name='Recipients'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['status', 'created_at'], name='async_notif_status_9e94c9_idx'),
        ),
    ]
