# Generated by Django 5.2.5 on 2026-07-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_notification', '0003_remove_emailnotification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='base_template',
            field=models.CharField(blank=True, default='', help_text='Base template key from settings to wrap the content', max_length=150, verbose_name='Base Template'),
        ),
        migrations.AddField(
            model_name='newslettertemplate',
            name='base_template',
            field=models.CharField(blank=True, default='', help_text='Base template key from settings to wrap the content', max_length=150, verbose_name='Base Template'),
        ),
    ]
