# Generated by Django 5.2.5 on 2026-07-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_notification', '0004_newsletter_base_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='sent_recipients',
            field=models.JSONField(blank=True, default=list, help_text='Addresses already delivered; a retry resumes from here instead of re-sending already-delivered batches', verbose_name='Delivered Recipients'),
        ),
    ]
