# Generated by Django 6.0.3 on 2026-03-16 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_notification', '0004_emailtemplate_context_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='base_template',
            field=models.ForeignKey(blank=True, help_text="Parent template whose {{ body }} receives this template's rendered content", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='async_notification.emailtemplate', verbose_name='Base Template'),
        ),
        migrations.RunSQL(
            "UPDATE async_notification_emailtemplate SET base_template_id = NULL WHERE base_template_id = ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
