# Generated by Django 5.2.5 on 2026-07-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_notification', '0005_emailnotification_sent_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('granted', models.BooleanField(default=True, verbose_name='Granted')),
                ('source', models.CharField(blank=True, default='', max_length=150, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Consent',
                'verbose_name_plural': 'Email Consents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('reason', models.CharField(choices=[('unsubscribe', 'Unsubscribed'), ('complaint', 'Spam complaint'), ('bounce', 'Hard bounce'), ('manual', 'Manual')], default='unsubscribe', max_length=20, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Suppression',
                'verbose_name_plural': 'Email Suppressions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='is_promotional',
            field=models.BooleanField(default=False, help_text='Marketing/promotional email: adds one-click unsubscribe headers, honors the suppression list, and is sent one message per recipient. Leave off for transactional mail (password resets, receipts, etc.).', verbose_name='Promotional'),
        ),
    ]
