# Generated by Django 6.0.3 on 2026-03-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_notification', '0005_emailtemplate_base_template_fk'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettertemplate',
            name='model_base',
        ),
        migrations.AddField(
            model_name='newslettertemplate',
            name='model_base',
            field=models.ManyToManyField(blank=True, help_text='Models whose fields are available as newsletter template variables', to='contenttypes.contenttype', verbose_name='Model Base'),
        ),
    ]
