# Generated by Django 5.2.5 on 2026-07-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_notification', '0006_emailconsent_emailsuppression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettertask',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='newslettertask',
            name='sent_recipients',
            field=models.JSONField(blank=True, default=list, help_text='Addresses already delivered; a re-run resumes from here instead of re-sending to already-delivered recipients', verbose_name='Delivered Recipients'),
        ),
    ]
