# Generated by Django 6.0.3 on 2026-03-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_notification', '0006_newslettertemplate_model_base_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='max_retries',
            field=models.IntegerField(default=3, verbose_name='Max Retries'),
        ),
    ]
